# Generated by Django 4.0.5 on 2023-06-05 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_handle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('info', models.TextField(verbose_name='介绍')),
            ],
            options={
                'verbose_name': '介绍信息',
                'verbose_name_plural': '介绍信息',
                'db_table': 'db_info',
            },
        ),
    ]
